"""Seed blog posts dataset for Phitopolis Heimdall CMS."""

# ruff: noqa: E501

SEED_BLOG_POSTS: list[dict] = [
    {
        'slug': 'likhapolis-pagbibigay-kulay-at-saya',
        'title': 'LikhaPolis: Pagbibigay Kulay at Saya',
        'category': 'Community & CSR',
        'excerpt': 'For the latest CSR day, we, the new interns, were given the responsibility to organize the event, and from that, Project LikhaPolis was born.',
        'body': 'For the latest CSR day, we, the new interns, were given the responsibility to organize the event, and from that, Project LikhaPolis was born: an event to give back to the community by donating toys and gifts and ultimately put a smile on children’s faces.\n\n/images/blog/likhapolis-pagbibigay-kulay-at-saya/01.png\n\nGoing into our internship, we thought we would be entering the corporate world: white desks and the cold breeze of air conditioning. That was partly true, but we never expected to be giving gifts to kids in a daycare center.\n\nAlong with the incredibly helpful teachers at Taguig SIBOL Integrated School, we gave out building blocks, coloring books and materials, school supplies, and snacks and drinks for the kids.\n\n/images/blog/likhapolis-pagbibigay-kulay-at-saya/02.jpg\n\nAt first, the kids were rowdy, some were shy, and some didn’t like us when we first talked to them. But as they built houses, created robots and dinosaurs living in those houses (or in a deathmatch), or just random towers of blocks, seeing them smile and open up as they unleashed their creativity made our efforts all the more worth it.\n\n/images/blog/likhapolis-pagbibigay-kulay-at-saya/03.jpg\n\nWas it tiring? Yes, but giving back to the community, seeing the next generation, and watching them have fun, make friends, and enjoy their lives made this an internship experience none of us will ever forget, and one we will always value.\n\n/images/blog/likhapolis-pagbibigay-kulay-at-saya/04.jpg',
        'image_url': None,
        'author': 'Derven Gonzales',
        'status': 'published',
        'published_on': '2026-07-17',
        'featured': True,
    },
    {
        'slug': 'ready-set-school-brigada-eskwela-at-pembo-elementary-school',
        'title': 'Ready, Set, School: Brigada Eskwela at Pembo Elementary School',
        'category': 'People',
        'excerpt': 'For our second quarter CSR activity, our team had the privilege of joining the Brigada Eskwela initiative at Pembo Elementary School.',
        'body': 'For our second quarter CSR activity, our team had the privilege of joining the Brigada Eskwela initiative at Pembo Elementary School, DepEd’s annual school maintenance program that brings communities together to prepare schools for the incoming school year. It was a morning of sleeves rolled up, mops in hand, and smiles exchanged, and we wouldn’t have had it any other way.\n\n/images/blog/ready-set-school-brigada-eskwela-at-pembo-elementary-school/01.jpg\n\nAlongside the dedicated teachers and school staff of Pembo Elementary, our volunteers dove into the work that makes a classroom feel like a safe and welcoming place to learn.',
        'image_url': None,
        'author': 'Daryn Ampil, Josua Costibolo',
        'status': 'published',
        'published_on': '2026-05-21',
        'featured': False,
    },
    {
        'slug': '2026-technical-graduate-batch-1-onboarding-week',
        'title': '2026 Technical Graduate Batch 1 Onboarding Week',
        'category': 'People',
        'excerpt': 'Day 1 of onboarding week was a blast. We met our batchmates and future mentors, hyped each other up with group cheers, and built with LEGO.',
        'body': '/images/blog/2026-technical-graduate-batch-1-onboarding-week/01.png\n\nDay 1 of onboarding week was a blast. We met our batchmates and future mentors, hyped each other up with group cheers, and then got handed a pile of LEGO bricks with a deceptively tricky challenge — build a house, but nothing about it was straightforward.\n\nDay 2 was a chill day; it began with an office tour. We roamed around the 27th floor, exploring the office space and facilities like the sleeping quarters and the shower room.',
        'image_url': None,
        'author': 'John Caleb Tan, Wray Nathan Andres',
        'status': 'published',
        'published_on': '2026-05-12',
        'featured': False,
    },
    {
        'slug': 'ai-day-2-0-smarter-systems-faster-teams',
        'title': 'AI Day 2.0: Smarter Systems, Faster Teams',
        'category': 'People',
        'excerpt': 'AI Day 2.0 kicked off the best way possible, with popcorn, juice, and a room full of curious minds ready to explore how AI is shaping work.',
        'body': 'AI Day 2.0 kicked off the best way possible, with popcorn, juice, and a room full of curious minds ready to explore how AI is shaping the way we work.\n\n/images/blog/ai-day-2-0-smarter-systems-faster-teams/01.png\n\nThe CTO opened the event by grounding everyone in a powerful idea. AI is no longer something we plan for in the future. It is already here, actively helping teams become faster, more efficient, and more focused on meaningful work.',
        'image_url': None,
        'author': 'Daryn Ampil, Josua Costibolo',
        'status': 'published',
        'published_on': '2026-04-14',
        'featured': False,
    },
    {
        'slug': 'sunshine-stories-and-school-kits-a-csr-day-to-remember',
        'title': 'Sunshine, Stories, and School Kits: A CSR Day to Remember',
        'category': 'People',
        'excerpt': 'There’s something truly special about a room full of kindergartners buzzing with excitement! For our latest CSR Day at East Rembo.',
        'body': 'There’s something truly special about a room full of kindergartners buzzing with excitement! For our latest CSR Day at the Barangay East Rembo Covered Court, we got to be right in the middle of it all.\n\n/images/blog/sunshine-stories-and-school-kits-a-csr-day-to-remember/01.jpg',
        'image_url': None,
        'author': 'Gabrielle Constantino',
        'status': 'published',
        'published_on': '2026-04-07',
        'featured': False,
    },
    {
        'slug': 'out-of-office-phitopolis-summer-2026',
        'title': 'Out of Office: Phitopolis Summer 2026',
        'category': 'People',
        'excerpt': 'If summer had a personality, ours would definitely be that one friend who is loud, game for anything, and always hungry.',
        'body': 'If summer had a personality, ours would definitely be that one friend who is loud, game for anything, always hungry, and somehow still full of energy after everything. This year’s Phitopolis Summer Outing brought that vibe to life as we headed to Hannah’s Garden in Calamba, Laguna.',
        'image_url': None,
        'author': 'Daryn Ampil',
        'status': 'published',
        'published_on': '2026-04-01',
        'featured': False,
    },
    {
        'slug': '2026-wellness-week',
        'title': '2026 Wellness Week',
        'category': 'People',
        'excerpt': 'Running Through BGC After office hours at 4:30 PM, a few colleagues managed to run together around BGC.',
        'body': 'Running Through BGC\n\nAfter office hours at 4:30 PM, a few colleagues managed to run together around BGC—something we had been planning since our company’s Wellness Week but couldn’t push through due to the constant rain.',
        'image_url': None,
        'author': 'Paolo Medina, Jumarie Mocon',
        'status': 'published',
        'published_on': '2026-03-27',
        'featured': False,
    },
    {
        'slug': '2024-technical-graduates-batch-1-two-years-milestones-of-growth',
        'title': '2024 Technical Graduates Batch 1: Two Years, Milestones of Growth',
        'category': 'People',
        'excerpt': 'It started with iced tea, appetizers, and familiar faces walking in, then quickly turned into a night no one will forget.',
        'body': 'It started with iced tea, appetizers, and familiar faces walking in, then quickly turned into a night no one will forget. As Grads Batch 1 of 2024 reached their two-year milestone at Phitopolis, the room filled with laughter, stories, and a shared sense of pride.',
        'image_url': '/images/blog/2024-technical-graduates-batch-1-two-years-milestones-of-growth/05.jpg',
        'author': 'Daryn Ampil',
        'status': 'published',
        'published_on': '2026-02-18',
        'featured': False,
    },
    {
        'slug': 'game-on-boomerang-fu-brings-the-heat-and-the-chaos',
        'title': 'Game On: Boomerang Fu Brings the Heat (and the Chaos)',
        'category': 'People',
        'excerpt': 'What happens when you take a group of professionals fresh out of a monthly spotlight meeting and arm them with virtual boomerangs?',
        'body': 'What happens when you take a group of professionals fresh out of a monthly spotlight meeting and arm them with virtual boomerangs? Pure, glorious chaos, that’s what.\n\nLast January 29, the Phitopolis common area transformed into a battleground as six teams threw down in an epic Boomerang Fu tournament.',
        'image_url': None,
        'author': 'Gabrielle Constantino',
        'status': 'published',
        'published_on': '2026-02-06',
        'featured': False,
    },
    {
        'slug': 'joy-in-every-bag-christmas-gift-giving-at-brgy-pinagsama',
        'title': 'Joy in Every Bag: Christmas Gift Giving at Brgy. Pinagsama',
        'category': 'Community & CSR',
        'excerpt': 'It’s that time of the year again when giving back takes center stage, as we bring Christmas cheer to the children of Barangay Pinagsama.',
        'body': 'It’s that time of the year again when giving back takes center stage, as we bring Christmas cheer to the children of Barangay Pinagsama. This year, despite a light drizzle, Phitopolis brought the holiday spirit to life.',
        'image_url': None,
        'author': 'Bea Franco',
        'status': 'published',
        'published_on': '2025-12-18',
        'featured': False,
    },
]
